<a href="https://colab.research.google.com/github/olesyasha88/numpy_solutions/blob/main/Numpy_solutions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

print(np.zeros(10, dtype=int))

[0 0 0 0 0 0 0 0 0 0]


In [2]:
print(np.ones(10, dtype=int))

[1 1 1 1 1 1 1 1 1 1]


In [3]:
print(np.repeat(5, 10))

[5 5 5 5 5 5 5 5 5 5]


In [4]:
print(np.arange(10, 51, dtype=int))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [5]:
print(np.arange(10, 51, 2, dtype=int))

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [6]:
print(np.arange(0, 9).reshape((3, 3)))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [7]:
print(np.ones((3, 3), dtype=int))

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [8]:
print(np.random.uniform(0, 1))

0.9698721464988718


In [9]:
print(np.random.normal(0,1,25))

[-0.46072028  2.72540586 -0.81711914  0.03575318  1.57794161 -0.3953114
 -0.42733823  0.12599998  0.27021159 -0.6413308  -1.56469659 -0.82689839
  0.86379457  1.28830661 -2.56327439  0.58443738  0.50873204 -0.05007763
  0.61365013  0.31587432 -0.69487329 -1.30336737 -1.30693398 -1.56605397
  0.27385973]


In [11]:
print(np.arange(0.01, 1.01, .01, dtype=float).reshape((10, 10)))

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


In [12]:
mat = np.arange(1, 26).reshape(5, 5)
print("Стартовая матрица: \n{}\n\n".format(mat))

print(mat[2:, 1:])



Стартовая матрица: 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [13]:
print(mat[3,4])

20


In [14]:
print(mat[0:3, 1:2])

[[ 2]
 [ 7]
 [12]]


In [15]:
print(mat[4:, 0:])

[[21 22 23 24 25]]


In [16]:
print(mat[3:,0:])

[[16 17 18 19 20]
 [21 22 23 24 25]]


In [17]:
print(np.sum(mat))

325


In [19]:
print(np.sum(mat, 0))

[55 60 65 70 75]
